### ISSUE TITLE
searchgui: FastaCLI fails with getting user preferences from home dir

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproteomics/tools-galaxyp#293]
SearchGUI fails with: 

```
An error occurred while saving /home/petrusch/.compomics/userpreferences.cup (see below).
java.io.FileNotFoundException: /home/petrusch/.compomics/userpreferences.cup (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.compomics.util.io.SerializationUtils.writeObject(SerializationUtils.java:23)
	at com.compomics.util.preferences.UtilitiesUserPreferences.saveUserPreferences(UtilitiesUserPreferences.java:626)
	at com.compomics.util.preferences.UtilitiesUserPreferences.loadUserPreferences(UtilitiesUserPreferences.java:645)
	at eu.isas.searchgui.cmd.FastaCLI.generateTargetDecoyDatabase(FastaCLI.java:169)
	at eu.isas.searchgui.cmd.FastaCLI.call(FastaCLI.java:119)
	at eu.isas.searchgui.cmd.FastaCLI.<init>(FastaCLI.java:59)
	at eu.isas.searchgui.cmd.FastaCLI.main(FastaCLI.java:218)
```

The file actually does not exist. However, in Galaxy user preferences from the user HOME should not be used anyway. This is particularly bad for Galaxies running jobs as real user. 

To solve this we need to make fastaCLI work without the preferences or to autogenerate  and use preferences in the job working directory.

**Comment by bgruening** [comment]
@bernt-matthias wouldn't it be enough to set $HOME inside the Galaxy wrapper to /tmp or similar?

**Comment by bernt-matthias** [comment]
Hmm. Maybe I should rather consider this as a configuration problem and set `shared_home_dir` in galaxy's config.  

But I'm not sure if the will have any effect, since @jmchilton's PR only creates `JOBDIR/home` and some galaxy variables, but leaves `$HOME` seemingly untouched. But I will try it these days.

**Comment by bernt-matthias** [comment]
Just have seen that $HOME is already set. Trying to fix now based on comments in https://github.com/compomics/searchgui/issues/107 but ran into a now problem: https://github.com/compomics/searchgui/issues/180

**Comment by bernt-matthias** [comment]
Notes to myself:

- [ ] add -temp_folder to SearchGUI call

**Comment by hbarsnes** [comment]
Simply adding the `-temp_folder` option to the FastaCLI command line should solve this issue.

See my other comments on the temp folder issues here: https://github.com/compomics/searchgui/issues/180
