### ISSUE TITLE
problems with meta proteome analyzer

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproteomics/tools-galaxyp#547]
ping @chambm 

Still having problems with MPA. Input is a 600MB fasta file and 441MB mgf. Might be a memory problem, but -Xmx 70GB is already quite a lot (actual available memory was 3 * 37GB). 

Any ideas what we could try here?

stderr
```
Picked up _JAVA_OPTIONS: -Xmx70g -Xms256m
java.lang.NullPointerException
	at org.mapdb.DataOutput2.writeUTF(DataOutput2.java:148)
	at org.mapdb.serializer.SerializerString.serialize(SerializerString.java:15)
	at org.mapdb.serializer.SerializerString.serialize(SerializerString.java:11)
	at org.mapdb.serializer.SerializerArrayTuple.valueArraySerialize(SerializerArrayTuple.java:62)
	at org.mapdb.BTreeMapJava$NodeSerializer.serialize(BTreeMapJava.java:166)
	at org.mapdb.BTreeMapJava$NodeSerializer.serialize(BTreeMapJava.java:136)
	at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:243)
	at org.mapdb.StoreDirect.update(StoreDirect.kt:631)
	at org.mapdb.BTreeMap.put2(BTreeMap.kt:408)
	at org.mapdb.BTreeMap.put(BTreeMap.kt:292)
	at org.mapdb.BTreeMapJava$KeySet.add(BTreeMapJava.java:529)
	at de.mpa.io.fasta.index.OffHeapIndex.addToPeptideIndex(OffHeapIndex.java:130)
	at de.mpa.io.fasta.index.OffHeapIndex.generateIndex(OffHeapIndex.java:104)
	at de.mpa.io.fasta.index.OffHeapIndex.setupDatabase(OffHeapIndex.java:76)
	at de.mpa.io.fasta.index.OffHeapIndex.<init>(OffHeapIndex.java:58)
	at de.mpa.cli.CmdLineInterface.call(CmdLineInterface.java:222)
	at de.mpa.cli.CmdLineInterface.<init>(CmdLineInterface.java:79)
	at de.mpa.cli.CmdLineInterface.main(CmdLineInterface.java:335)
```

stdout
```
X!Tandem
DB: Merged and Filtered FASTA from data 104, data 103, and others sequences: 1260552
Spectrums:2020-06-10_LK_P24_HEW4-PA(API:9e655f38e58ae482) 
Tue Jan 26 11:12:23 CET 2021 Creating FASTA index file...
Tue Jan 26 11:31:23 CET 2021 FASTA index file creation finished...
Tue Jan 26 11:31:23 CET 2021 Creating FASTA decoy file...
Tue Jan 26 11:31:26 CET 2021 FASTA decoy file creation finished...
Tue Jan 26 11:31:26 CET 2021 Creating peptide index file...
```

**Comment by chambm** [comment]
Did you mean to ping someone else?

**Comment by bernt-matthias** [comment]
Ups. My bad :) Seems that I mixed up my memory ..
