### ISSUE TITLE
Peptideshaker: only allow compatible searchgui input

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproteomics/tools-galaxyp#651]
Searchgui input should be allowed only for compatible versions. 

Or at least documented which versions are allowed.

**Comment by bernt-matthias** [comment]
Actually it should: https://github.com/galaxyproteomics/tools-galaxyp/blob/d08008686fd3cace19449ac950c4e0864b7a8ef8/tools/peptideshaker/peptide_shaker.xml#L283

But apparently it does not: 

```
 inflated: SEARCHGUI_IdentificationParameters.par
An error occurred when saving the path preference to /gpfs1/data/galaxy_server/galaxy/database/dependencies/_conda/envs/mulled-v1-778f36fa238af9daffe7e1e078d5d379b2e631a2f9db740ac57a49bbe2530526/share/peptide-shaker-2.0.25-0/resources/conf/paths.txt.
	at com.compomics.util.io.flat.SimpleFileWriter.<init>(SimpleFileWriter.java:59)
	at eu.isas.peptideshaker.preferences.PeptideShakerPathParameters.writeConfigurationToFile(PeptideShakerPathParameters.java:391)
	at eu.isas.peptideshaker.cmd.PathSettingsCLI.setPathSettings(PathSettingsCLI.java:114)
	at eu.isas.peptideshaker.cmd.PathSettingsCLI.extractAndUpdatePathOptions(PathSettingsCLI.java:273)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1356)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at com.compomics.util.io.flat.SimpleFileWriter.<init>(SimpleFileWriter.java:53)
	... 4 more
<CompomicsError>PeptideShaker processing failed. Please see the PeptideShaker log file.</CompomicsError>
java.lang.IllegalArgumentException: Version of parameters file /work/songalax/galaxy/database/jobs_directory/000/149/149046/working/SEARCHGUI_IdentificationParameters.par not supported.
	at com.compomics.util.parameters.identification.IdentificationParameters.getIdentificationParameters(IdentificationParameters.java:557)
	at com.compomics.cli.identification_parameters.IdentificationParametersInputBean.<init>(IdentificationParametersInputBean.java:2102)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLIInputBean.<init>(PeptideShakerCLIInputBean.java:152)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1377)
```

**Comment by bernt-matthias** [comment]
User used PS 2.0.25+galaxy0 with an output from SG 3.3.10.1. The metadata of the SG correctly shows 

SearchGui Version: 3.3.10.1 and 
SearchGui Major Version 3

So the tool should actually not allow to load this SG input ... and if I try to reproduce it doesn't .. really odd .. will try to ask the user if he recalls how he got this data in.
